### ISSUE TITLE
Note 11T pro(+) 测试探讨

### ISSUE THREAD

**Issue by szkzn** [ljc-fight/erofs2ext4Converter-for-MIUI-Device#2]
解包修改完成之后
是先执行 flash-format.bat  ，再执行 flash-update.bat 吗？

**Comment by szkzn** [comment]
![image](https://p.0z.gs/i/2022/12/03/638a9eb6b53c0.png)

**Comment by szkzn** [comment]
我把过程写到这里了
https://www.0z.gs/android/1845.html
但是翻车了 最后步骤找不到路径，我看了下脚本末尾阶段，写的是相对路径 /bin/xxxxx，

> bin\fastboot erase userdata
bin\fastboot erase metadata
bin\fastboot set_active a
bin\fastboot reboot

我检查了当前目录下的路径，`erofs2ext4Converter-for-MIUI-Device-main\bin`下面只有

Linux---------------------目录
platform-tools-----------目录
Windows-----------------目录
flash-format.bat----------文件
flash-update.bat----------文件

但是应该也没问题，fastboot 路径是写到了系统环境变量了
我现在不知道那一串找不到指定路径是什么问题，还是其他过程错了呢？

手机是 Redmi Note 11T Pro +， MIUI 13.0.11.0 稳定版

**Comment by saYmd-moe** [comment]
我尝试把这个脚本输出的images文件夹和从官网下载的同版本线刷包中的images文件夹合并，直接覆盖后再刷入可以成功，估计是作者的flash-format和flash-update脚本有些问题

**Comment by saYmd-moe** [comment]
> 覆盖后开机，system 等 erofs 分区转换成功了吗，转换成 ext4成功的话，那是否可以 写入了？

尝试了system分区可以正常写入

**Comment by ghost** [comment]
![图片](https://user-images.githubusercontent.com/58981364/235629443-733ea630-81d2-4c0c-b69b-a49d91b2d7c7.png)
我这个样子我都不敢刷

**Comment by MCTVVTCM** [comment]
> 我尝试把这个脚本输出的images文件夹和从官网下载的同版本线刷包中的images文件夹合并，直接覆盖后再刷入可以成功，估计是作者的flash-format和flash-update脚本有些问题

请问你是拿官方线刷脚本刷的还是用项目生成脚本刷的

**Comment by saYmd-moe** [comment]
> > 我尝试把这个脚本输出的images文件夹和从官网下载的同版本线刷包中的images文件夹合并，直接覆盖后再刷入可以成功，估计是作者的flash-format和flash-update脚本有些问题
> 
> 请问你是拿官方线刷脚本刷的还是用项目生成脚本刷的

官方线刷脚本，这个程序生成的脚本应该有问题

**Comment by MCTVVTCM** [comment]
> > > 我尝试把这个脚本输出的images文件夹和从官网下载的同版本线刷包中的images文件夹合并，直接覆盖后再刷入可以成功，估计是作者的flash-format和flash-update脚本有些问题
> > 
> > 
> > 请问你是拿官方线刷脚本刷的还是用项目生成脚本刷的
> 
> 官方线刷脚本，这个程序生成的脚本应该有问题

谢谢，我注意到生成的脚本内没有刷入super分区
