### ISSUE TITLE
k50u的官方卡刷包好像无法重新打包

### ISSUE THREAD

**Issue by NavlysChen** [ljc-fight/erofs2ext4Converter-for-MIUI-Device#4]
请问大佬，我应该怎么解决这个问题？
```
error: build_directory_structure: cannot lookup security context for /system/lost+found
Failed to create image tmp/output/system.img, removing it

Error: - "Failed to repack system.img with ext4 format"
_Tips: - "Details are above"‘’
```

**Comment by ljc-fight** [comment]
重新上传了新的，可以再试试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ljc-fight/erofs2ext4Converter-for-MIUI-Device"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 晚上9:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ljc-fight/erofs2ext4Converter-for-MIUI-Device] k50u的官方卡刷包好像无法重新打包 (Issue #4)





 
请问大佬，我应该怎么解决这个问题？
 error: build_directory_structure: cannot lookup security context for /system/lost+found Failed to create image tmp/output/system.img, removing it Error: - "Failed to repack system.img with ext4 format" _Tips: - "Details are above"‘’

**Comment by NavlysChen** [comment]
> 重新上传了新的，可以再试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ljc-fight/erofs2ext4Converter-for-MIUI-Device" ***@***.***&gt;; 发送时间:&nbsp;2022年12月1日(星期四) 晚上9:20 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[ljc-fight/erofs2ext4Converter-for-MIUI-Device] k50u的官方卡刷包好像无法重新打包 (Issue #4) 请问大佬，我应该怎么解决这个问题？ error: build_directory_structure: cannot lookup security context for /system/lost+found Failed to create image tmp/output/system.img, removing it Error: - "Failed to repack system.img with ext4 format" _Tips: - "Details are above"‘’ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

非常感谢，已经可以了
